import { useEffect, useState } from "react";
import { CalendarDays, Download, FileSpreadsheet, Plus } from "lucide-react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/agila/app-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { workspaceApi, type Report } from "@/lib/workspace-api";

const tooltipStyle = { borderRadius: 12, border: "1px solid var(--border)", background: "var(--popover)", color: "var(--popover-foreground)", fontSize: 12 };
function downloadCsv(csv: string, name: string) { const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `${name}.csv`; link.click(); URL.revokeObjectURL(url); }

export default function ReportsPage() {
  const [type, setType] = useState("Daily summary"); const [scope, setScope] = useState("All grade levels"); const [period, setPeriod] = useState("Today");
  const [weekly, setWeekly] = useState<{ day: string; present: number; late: number; absent: number }[]>([]); const [grades, setGrades] = useState<{ grade: string; rate: number }[]>([]); const [reports, setReports] = useState<Report[]>([]); const [message, setMessage] = useState("");
  const load = async () => { try { const result = await workspaceApi.reports(); setWeekly(result.weekly); setGrades(result.gradeBreakdown); setReports(result.reports); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load reports"); } };
  useEffect(() => { void load(); }, []);
  const create = async () => { try { const result = await workspaceApi.createReport({ type, scope, period }); downloadCsv(result.csv, result.report.name.replace(/\s+/g, "-")); await load(); setMessage("Report generated and downloaded."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to generate report"); } };
  return <AppShell title="Reports" description="Build and export live attendance intelligence" actions={<><Button variant="outline" className="rounded-xl bg-surface" onClick={() => setMessage("Scheduled delivery requires a configured email provider.")}><CalendarDays className="size-4" /> Schedule</Button><Button className="rounded-xl" onClick={create}><Plus className="size-4" /> New report</Button></>}>
    <Card className="rounded-2xl border-border/70 shadow-card"><CardHeader><CardTitle className="font-display text-base">Report builder</CardTitle><p className="text-xs text-muted-foreground">Exports a CSV from your workspace attendance data</p></CardHeader><CardContent className="grid gap-3"><Select value={type} onValueChange={setType}><SelectTrigger className="h-11 rounded-xl"><SelectValue /></SelectTrigger><SelectContent>{["Daily summary", "Weekly tardiness", "Monthly rate", "Guardian log", "Watchlist"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={scope} onValueChange={setScope}><SelectTrigger className="h-11 rounded-xl"><SelectValue /></SelectTrigger><SelectContent>{["All grade levels", "Junior high", "Senior high", "Single section"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={period} onValueChange={setPeriod}><SelectTrigger className="h-11 rounded-xl"><SelectValue /></SelectTrigger><SelectContent>{["Today", "This week", "This month", "Quarter 1"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Button className="h-11 rounded-xl" onClick={create}><Download className="size-4" /> Generate export</Button>{message && <p className="text-sm text-muted-foreground">{message}</p>}</CardContent></Card>
    <div className="space-y-4"><Card className="rounded-2xl border-border/70 shadow-card"><CardHeader><CardTitle className="font-display text-base">Present vs late</CardTitle></CardHeader><CardContent className="h-72 pl-0"><ResponsiveContainer width="100%" height="100%"><LineChart data={weekly}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false} /><XAxis dataKey="day" /><YAxis width={44} /><Tooltip contentStyle={tooltipStyle} /><Legend /><Line type="monotone" dataKey="present" stroke="var(--chart-1)" /><Line type="monotone" dataKey="late" stroke="var(--chart-3)" /><Line type="monotone" dataKey="absent" stroke="var(--chart-4)" /></LineChart></ResponsiveContainer></CardContent></Card><Card className="rounded-2xl border-border/70 shadow-card"><CardHeader><CardTitle className="font-display text-base">Rate by grade level</CardTitle></CardHeader><CardContent className="space-y-4">{[...grades].sort((a, b) => b.rate - a.rate).map((grade) => <div key={grade.grade}><div className="flex justify-between text-sm"><span>{grade.grade}</span><b>{grade.rate}%</b></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-navy" style={{ width: `${grade.rate}%` }} /></div></div>)}</CardContent></Card></div>
    <Card className="rounded-2xl border-border/70 shadow-card"><CardHeader><CardTitle className="font-display text-base">Generated reports</CardTitle></CardHeader><CardContent className="space-y-3">{reports.map((report) => <div key={report.id} className="flex items-center gap-3 rounded-2xl border border-border/70 bg-surface p-3"><FileSpreadsheet className="size-5 text-primary" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{report.name}</p><p className="text-xs text-muted-foreground">{report.scope} · {report.period} · {report.size}</p></div><Download className="size-4 text-muted-foreground" /></div>)}</CardContent></Card>
  </AppShell>;
}
