import { useCallback, useEffect, useState } from "react";
import { Mail, Plus, Search } from "lucide-react";
import { AppShell } from "@/components/agila/app-shell";
import { StatCard } from "@/components/agila/stat-card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { initials } from "@/lib/agila-data";
import { peopleApi } from "@/lib/people-api";
import type { Teacher } from "@/lib/agila-data";

export default function TeachersPage() {
  const [items, setItems] = useState<Teacher[]>([]); const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false); const [invite, setInvite] = useState(""); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ name: "", email: "", department: "", advisory: "" });
  const load = useCallback(async () => { try { const result = await peopleApi.teachers(query); setItems(result.teachers); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load faculty"); } }, [query]);
  useEffect(() => { void load(); }, [load]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); try { await peopleApi.createTeacher(form); setForm({ name: "", email: "", department: "", advisory: "" }); setShowForm(false); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to add teacher"); } };
  const sendInvite = async (event: React.FormEvent) => { event.preventDefault(); try { await peopleApi.inviteTeacher(invite); setInvite(""); setMessage("Invitation queued."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to invite faculty"); } };
  return <AppShell title="Teachers" description={`${items.length} faculty members in the directory`} actions={<><Button variant="outline" className="rounded-xl bg-surface" onClick={() => { const email = window.prompt("Faculty email"); if (email) { setInvite(email); void peopleApi.inviteTeacher(email).then(() => setMessage("Invitation queued.")).catch((error) => setMessage(error.message)); } }}><Mail className="size-4" /> Invite faculty</Button><Button className="rounded-xl" onClick={() => setShowForm((value) => !value)}><Plus className="size-4" /> Add teacher</Button></>}>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><StatCard label="Faculty" value={String(items.length)} delta="live" trend="up" hint="from directory" /><StatCard label="Advisers" value={String(items.filter((item) => item.advisory).length)} delta="live" trend="flat" hint="sections covered" /><StatCard label="Confirmed today" value="—" delta="" trend="flat" hint="attendance report pending" /><StatCard label="On leave" value={String(items.filter((item) => item.status === "on leave").length)} delta="live" trend="flat" hint="from directory" /></div>
    {showForm && <Card className="rounded-2xl border-border/70 shadow-card"><CardContent className="p-4"><form onSubmit={create} className="grid gap-2 sm:grid-cols-2">{([['name', 'Full name'], ['email', 'Email'], ['department', 'Department'], ['advisory', 'Advisory (optional)']] as const).map(([key, label]) => <Input key={key} required={key !== 'advisory'} placeholder={label} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} />)}<Button type="submit" className="rounded-xl sm:col-span-2">Save teacher</Button></form></CardContent></Card>}
    <form onSubmit={sendInvite} className="flex gap-2"><Input type="email" value={invite} onChange={(event) => setInvite(event.target.value)} placeholder="Invite faculty by email" className="rounded-xl" /><Button type="submit" variant="outline" className="rounded-xl">Invite</Button></form>
    <Card className="rounded-2xl border-border/70 shadow-card"><CardContent className="p-5"><div className="relative max-w-md"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search faculty by name or department" className="h-10 rounded-xl pl-9" /></div>{message && <p className="mt-3 text-sm text-muted-foreground">{message}</p>}<div className="mt-5 grid gap-4">{items.map((teacher) => <div key={teacher.id} className="rounded-2xl border border-border/70 bg-surface p-5 transition-shadow hover:shadow-card"><div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3"><Avatar className="size-11 shrink-0"><AvatarFallback className="bg-navy text-sm text-navy-foreground">{initials(teacher.name)}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate font-semibold">{teacher.name}</p><p className="truncate text-xs text-muted-foreground">{teacher.email}</p></div><span className="shrink-0 rounded-full px-2.5 py-1 text-[11px] font-semibold capitalize">{teacher.status}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-muted-foreground">Department</dt><dd className="truncate font-medium">{teacher.department}</dd></div><div><dt className="text-xs text-muted-foreground">Classes</dt><dd className="font-medium">{teacher.classes} sections</dd></div><div className="col-span-2"><dt className="text-xs text-muted-foreground">Advisory</dt><dd className="truncate font-medium">{teacher.advisory || "Not assigned"}</dd></div></dl><div className="mt-4 flex gap-2"><Button variant="outline" size="sm" className="flex-1 rounded-lg bg-card" onClick={() => setMessage(`${teacher.name}: ${teacher.department}${teacher.advisory ? ` · ${teacher.advisory}` : ""}`)}>Profile</Button><Button size="sm" className="flex-1 rounded-lg" onClick={() => { window.location.href = `mailto:${teacher.email}`; }}>Message</Button></div></div>)}</div></CardContent></Card>
  </AppShell>;
}
